[package]
name = "acm-dtu-ux"
version = "0.1.0"
authors = [ "Demetrio Battaglia <https://deme3.me>" ]
license = "MIT"
description = "The ACM-based template for UX Design Prototyping / UX Engineering assignments at Technical University of Denmark (DTU)."
entrypoint = "template.typ"
categories = [ "paper", "report" ]
disciplines = [ "computer-science", "design" ]

[template]
path = "assets"
entrypoint = "main.typ"
thumbnail = ""
